<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>GoLive.UrlSigner.MinimalApis</PackageId>
        <Authors>SurgicalCoder</Authors>
        <Company>N/A</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Description>
            .net 10 Minimal API support for signed URLs and signed URL token validation
        </Description>
        <Copyright>Copyright 2021 - 2026 - SurgicalCoder</Copyright>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <GenerateRepositoryUrlAttribute>true</GenerateRepositoryUrlAttribute>
        <PackOnBuild>true</PackOnBuild>
        <LangVersion>11</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GoLive.UrlSigner\GoLive.UrlSigner.csproj" />
    </ItemGroup>

</Project>

