name: Publish to Nuget
on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  publish:
    env:
     SOLUTION: 'GoLive.UrlSigner.sln'
     BUILD_VER : '2.0'
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
      - name: Get Build Version
        run: |
          echo "BUILD_VERSION=$((BUILD_VER)).$((GITHUB_RUN_NUMBER))" >> $GITHUB_ENV
      - name: Output build number
        run: echo $(BUILD_VERSION)
      - name: Build
        run: dotnet pack $SOLUTION --configuration Release -p:Version=$BUILD_VERSION -p:PackageVersion=$BUILD_VERSION
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_KEY}}