name: Publish to Nuget
on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  publish:
    env:
        SOLUTION: 'GoLive.UrlSigner.sln'
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Get Build Version
        run: |
          echo "VERSION_NUMBER_WITH_OFFSET=2.0.$((BUILD_VERSION))" >> $GITHUB_ENV
      - name: Restore dependencies
        run: nuget restore $SOLUTION
      - name: Build
        run: dotnet build $SOLUTION --configuration Release -p:Version=$BUILD_VERSION --no-restore
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_KEY}}